#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude 'known-articles.json' \
	--exclude node_modules \
	. 'europa:~/bots/unusual-wikipedia-twitter-bot/'

ssh europa "\
cd ~/bots/unusual-wikipedia-twitter-bot
npm i
npm update
forever-service delete unusual-wikipedia-twitter-bot
forever-service install unusual-wikipedia-twitter-bot -e 'NODE_ENV=production ENV=production' --start -s index.js"
